const monthly = [
  {
    planeName: "BASIC",
    role: "Administration",
    price: 4,
    buttonColor: "#3d4853",
    List: [
      { title: "Add time for others" },
      { title: "Hide time and pages" },
      { title: "Required fields" },
      { title: "Bulk edit" },
      { title: "Decimal format" },
      { title: "Time audit" },
      { title: "Customize exports" },
      { title: "Project templates" },
      { title: "Historic rates" },
      { title: "Edit profiles" },
      { title: "Import timesheets" },
    ],
  },
  {
    planeName: "STANDARD",
    role: "Timesheeting & Billing",
    price: 6,
    buttonColor: "#2f80ed",
    List: [
      { title: "All BASIC features" },
      { title: "Time off" },
      { title: "Invoicing" },
      { title: "Approval" },
      { title: "Manager role" },
      { title: "Lock timesheet" },
      { title: "Targets & reminders" },
      { title: "Task rates" },
      { title: "Rounding" },
      { title: "QuickBooks Integration" },
      { title: "Force 2FA" },
    ],
  },
  {
    planeName: "PRO",
    role: "Profit & Productivity",
    price: 9,
    buttonColor: "#eb5757",
    List: [
      { title: "All STANDARD features" },
      { title: "Scheduling" },
      { title: "Expenses" },
      { title: "GPS tracking" },
      { title: "Screenshots" },
      { title: "Force timer" },
      { title: "Labor cost & profit" },
      { title: "Scheduled reports" },
      { title: "Budget & estimates" },
      { title: "Alerts" },
      { title: "Custom fields" },
      { title: "User fields" },
    ],
  },
  {
    planeName: "ENTERPRISE",
    role: "Control & Security",
    price: 14,
    buttonColor: "#9b51e0",
    List: [
      { title: "All PRO features" },
      { title: "Single sign-on (SSO)" },
      { title: "Custom subdomain" },
      { title: "Control accounts" },
      { title: "Audit log" },
    ],
  },
];


const annual = [
    {
      planeName: "BASIC",
      role: "Administration",
      price: 3,
      buttonColor: "#3d4853",
      List: [
        { title: "Add time for others" },
        { title: "Hide time and pages" },
        { title: "Required fields" },
        { title: "Bulk edit" },
        { title: "Decimal format" },
        { title: "Time audit" },
        { title: "Customize exports" },
        { title: "Project templates" },
        { title: "Historic rates" },
        { title: "Edit profiles" },
        { title: "Import timesheets" },
      ],
    },
    {
      planeName: "STANDARD",
      role: "Timesheeting & Billing",
      price: 5,
      buttonColor: "#2f80ed",
      List: [
        { title: "All BASIC features" },
        { title: "Time off" },
        { title: "Invoicing" },
        { title: "Approval" },
        { title: "Manager role" },
        { title: "Lock timesheet" },
        { title: "Targets & reminders" },
        { title: "Task rates" },
        { title: "Rounding" },
        { title: "QuickBooks Integration" },
        { title: "Force 2FA" },
      ],
    },
    {
      planeName: "PRO",
      role: "Profit & Productivity",
      price: 7,
      buttonColor: "#eb5757",
      List: [
        { title: "All STANDARD features" },
        { title: "Scheduling" },
        { title: "Expenses" },
        { title: "GPS tracking" },
        { title: "Screenshots" },
        { title: "Force timer" },
        { title: "Labor cost & profit" },
        { title: "Scheduled reports" },
        { title: "Budget & estimates" },
        { title: "Alerts" },
        { title: "Custom fields" },
        { title: "User fields" },
      ],
    },
    {
      planeName: "ENTERPRISE",
      role: "Control & Security",
      price: 11,
      buttonColor: "#9b51e0",
      List: [
        { title: "All PRO features" },
        { title: "Single sign-on (SSO)" },
        { title: "Custom subdomain" },
        { title: "Control accounts" },
        { title: "Audit log" },
      ],
    },
  ];

export { monthly ,annual};
